In [40]:
#PROGRAMMING ASSIGNMETN #2

In [41]:
#NORMALIZATION PROBLEM

In [42]:
import numpy as np

In [43]:
X = np.random.rand(5, 5)
print("Original Array X: ")
print(X)

Original Array X: 
[[0.07314389 0.94275098 0.53113552 0.74027017 0.55081683]
 [0.81490276 0.2630142  0.3885222  0.48940616 0.58528036]
 [0.55512396 0.3038149  0.36888654 0.48055862 0.44219498]
 [0.39720104 0.26806533 0.25088121 0.17544421 0.3609052 ]
 [0.97213991 0.02570634 0.42720068 0.81329862 0.6576848 ]]


In [44]:
mean = X.mean()
std = X.std()
print("Mean of X: ")
print(mean)
print("Standard Deviation of X: ")
print(std)

Mean of X: 
0.4751339764296775
Standard Deviation of X: 
0.24404343236786527


In [45]:
X_normalized = (X - mean) / std
print("Normalized Array: ")
print(X_normalized)

Normalized Array: 
[[-1.64720716  1.91612206  0.22947366  1.08643037  0.31012041]
 [ 1.39224718 -0.86918864 -0.35490312  0.05848215  0.45133928]
 [ 0.32776947 -0.7020024  -0.43536282  0.02222817 -0.13497187]
 [-0.31934044 -0.84849096 -0.91890514 -1.22801815 -0.4680674 ]
 [ 2.03654707 -1.84158872 -0.19641299  1.38567403  0.74802594]]


In [46]:
np.save('X_normalized.npy', X_normalized)
print("Normalized array saved as X_normalized.npy")

Normalized array saved as X_normalized.npy


In [47]:
#DIVISIBLE BY #3 PROBLEM

In [48]:
numbers = np.arange(1, 101)       
squares = numbers**2              
X = squares.reshape(10, 10)      
print("Array of the squares of the first 100 integers: ")
print(X)

Array of the squares of the first 100 integers: 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [49]:
div_by_3 = X[X % 3 == 0]         
print("Integers divisible by 3: ")
print(div_by_3)

Integers divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [50]:
np.save('div_by_3.npy', div_by_3)
print("Saved result as div_by_3.npy")

Saved result as div_by_3.npy
